Description: >
  Server template for a VPC with a Single Public Subnet


Parameters:

  EnvironmentName:
    Description: Name of the enviroment
    Type: String


Resources:

  WebServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow http to client host
        VpcId:
          Fn::ImportValue:
            !Sub "${EnvironmentName}-VPCID"
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  WebServer: 
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06d51e91cea0dac8d
      InstanceType: t2.micro
      NetworkInterfaces:
        - DeviceIndex: "0"
          SubnetId:
            Fn::ImportValue:
              !Sub "${EnvironmentName}-PUB1-SN"
          GroupSet: 
            - !GetAtt WebServerSecGroup.GroupId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y

    # WebServer:
    #     Type: AWS::EC2::Instance
    #     Properties:
    #         ImageId: ami-06d51e91cea0dac8d
    #         InstanceType: t2.micro
    #         SubnetId: !Ref PrivateSubnet1
    #         SecurityGroupIds:
    #         -   !Ref WebServerSecGroup

  WebServerEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref WebServer